name: Pipeline CI/CD - Gerenciador de Tarefas

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # 1. Job de Testes e Geração de Relatórios
  testes:
    name: 1. Execucao de Testes Unitarios
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar Testes (22+ cenários)
        run: mvn test

      - name: Armazenar Relatorio de Testes (Artefato)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: target/surefire-reports/

  # 2. Job de Build (Empacotamento)
  build:
    name: 2. Empacotamento JAR
    runs-on: ubuntu-latest
    needs: testes
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Criar Pacote JAR
        run: mvn package -DskipTests

      - name: Armazenar Pacote JAR (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: pacote-jar
          path: target/*.jar

  # 3. Job de Notificação Final
  notificacao:
    name: 3. Notificacao Final por Email
    runs-on: ubuntu-latest
    needs: [testes, build]
    if: always()
    steps:
      - name: Checkout do codigo e script
        uses: actions/checkout@v4

      - name: Tornar script de email executavel
        run: chmod +x scripts/enviar_email.sh

      - name: Verificar status dos trabalhos anteriores
        id: verificar_status
        run: |
          TESTE_STATUS="${{ needs.testes.result }}"
          BUILD_STATUS="${{ needs.build.result }}"
          
          if [ "$TESTE_STATUS" == "success" ] && [ "$BUILD_STATUS" == "success" ]; then
            STATUS_FINAL="SUCESSO"
          else
            STATUS_FINAL="FALHA"
          fi
          
          echo "STATUS_FINAL=$STATUS_FINAL" >> $GITHUB_OUTPUT
          echo "TESTE_STATUS=$TESTE_STATUS" >> $GITHUB_OUTPUT
          echo "BUILD_STATUS=$BUILD_STATUS" >> $GITHUB_OUTPUT

      - name: Enviar Email de Status
        env:
          EMAIL_DESTINO: "raissa.rodrigues@gec.inatel.br,matheus.mc@gec.inatel.br,tiago.tr@gec.inatel.br"
          SMTP_SERVER: "smtp.gmail.com"
          SMTP_PORT: "587"
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          ./scripts/enviar_email.sh "${{ steps.verificar_status.outputs.STATUS_FINAL }}" \
            "${{ steps.verificar_status.outputs.TESTE_STATUS }}" \
            "${{ steps.verificar_status.outputs.BUILD_STATUS }}"