name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn test
      - uses: actions/upload-artifact@v2
        with:
          name: relatorio-testes
          path: target/surefire-reports/

  build:
    runs-on: ubuntu-latest
    needs: testes
    steps:
      - uses: actions/checkout@v2
      - run: mvn package
      - uses: actions/upload-artifact@v2
        with:
          name: pacote-jar
          path: target/*.jar

  notificacao:
    runs-on: ubuntu-latest
    needs: [testes, build]
    steps:
      - uses: actions/checkout@v2
      - run: python3 ci/enviar_email.py
        env:
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
